### ISSUE TITLE
[/结算]同时结算多人点数

### ISSUE THREAD

**Issue by Cloud-cat** [ssttkkl/nonebot-plugin-mahjong-scoreboard#6]
希望能够实现同时结算四人点数，只需要发送一条指令就可以，目前四个人都发结算一共八条消息有点刷屏
![image](https://user-images.githubusercontent.com/42345561/220001436-434aaa3a-3294-4cdb-a998-48f53aeae478.png)

**Comment by ssttkkl** [comment]
这个实现起来有点困难，暂时不会考虑
________________________________
From: cloudcat ***@***.***>
Sent: Monday, February 20, 2023 11:15:48 AM
To: ssttkkl/nonebot-plugin-mahjong-scoreboard ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ssttkkl/nonebot-plugin-mahjong-scoreboard] [/结算]同时结算多人点数 (Issue #6)


希望能够实现同时结算四人点数，只需要发送一条指令就可以，目前四个人都发结算一共八条消息有点刷屏
[image]<https://user-images.githubusercontent.com/42345561/220001436-434aaa3a-3294-4cdb-a998-48f53aeae478.png>

―
