### ISSUE TITLE
能否将记分精确到小数点后一位

### ISSUE THREAD

**Issue by Ble55me** [ssttkkl/nonebot-plugin-mahjong-scoreboard#7]
感觉现在只保留整数位误差有点大了

**Comment by ssttkkl** [comment]
我们群的规则是小数部分直接切上所以直接写死了（）我看看在新建赛季的时候加个选项吧
________________________________
From: Ble55me ***@***.***>
Sent: Monday, February 20, 2023 11:59:34 AM
To: ssttkkl/nonebot-plugin-mahjong-scoreboard ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ssttkkl/nonebot-plugin-mahjong-scoreboard] 能否将记分精确到小数点后一位 (Issue #7)


感觉现在只保留整数位误差有点大了

―

**Comment by ssttkkl** [comment]
0.2.0版本现已实现创建赛季时配置PT精度
![QQ截图20230224182731](https://user-images.githubusercontent.com/17331698/221155927-daf90c0b-4ab1-405b-866c-c10206fa4a9a.png)
![QQ图片20230224182811](https://user-images.githubusercontent.com/17331698/221155939-225ca5f5-e5e1-4b36-963f-ba51965e5382.png)
