### ISSUE TITLE
加载插件报错

### ISSUE THREAD

**Issue by Ble55me** [ssttkkl/nonebot-plugin-mahjong-scoreboard#8]
在bot上装了新版本之后启动会报错，报错日志在这里
[log.txt](https://github.com/ssttkkl/nonebot-plugin-mahjong-scoreboard/files/11079588/log.txt)

**Comment by ssttkkl** [comment]
手动装下nonebot_plugin_gocqhttp_cross_machine_upload_file这个包呢

**Comment by Ble55me** [comment]
装完又出现了新的报错，日志是这样
[log1.txt](https://github.com/ssttkkl/nonebot-plugin-mahjong-scoreboard/files/11098480/log1.txt)

**Comment by ssttkkl** [comment]
估计是装了别的依赖SQLAlchemy2.0的插件导致冲突了，你更新这个插件到0.3.0看看

**Comment by Ble55me** [comment]
更新nonebot_plugin_gocqhttp_cross_machine_upload_file到0.3.0吗

**Comment by ssttkkl** [comment]
mahjong scoreboard
________________________________

**Comment by Ble55me** [comment]
不太行，更新到0.3.0之后又开始弹Failed to import "nonebot_plugin_gocqhttp_cross_machine_upload_file"，然后我又手动装这个包，还是弹这个报错，就是用不了

**Comment by Ble55me** [comment]
不太行，更新到0.3.0之后又开始弹Failed to import "nonebot_plugin_gocqhttp_cross_machine_upload_file"，然后我又手动装这个包，还是弹这个报错，就是用不了

**Comment by ssttkkl** [comment]
不知道什么问题，我这边是没问题的
你可以pip install nonebot-plugin-mahjong-scoreboard==0.3.0 --force-reinstall试试

**Comment by ssttkkl** [comment]
可以pip list看一看当前安装的包发出来看一下

**Comment by Ble55me** [comment]
pip list在这里
[pip.txt](https://github.com/ssttkkl/nonebot-plugin-mahjong-scoreboard/files/11134822/pip.txt)

**Comment by ssttkkl** [comment]
更新0.3.0.post1版本试试

**Comment by Ble55me** [comment]
更新完可以用了，感谢
